modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-3.0-or-later"
issueTrackerURL="https://github.com/quat1024/incorporeal-2-forge/issues"

[[mods]]
modId="incorporeal"
version="${file.jarVersion}"
displayName="Incorporeal 2"
displayURL="https://github.com/quat1024/incorporeal-2-forge/"
#logoFile="examplemod.png" #TODO
credits="Dudblockman and SnazzGass for some textures. And a very special thanks to all the Botania nerds over the years, you're the best." #optional
authors="quaternary"
description="Botania addon. More toys and tools for large-scale corporea networks."

[[mods]]
modId="rhododendrite"
version="${file.jarVersion}"
displayName="Rhododendrite"
displayURL="https://github.com/quat1024/incorporeal-2-forge/"
#logoFile="examplemod.png" #TODO
authors="quaternary"
description="Component of Incorporeal. Tree-based computing."

[[dependencies.incorporeal]]
    modId="botania"
    mandatory=true #mandatory
    versionRange="[1.16.5-419,)"
    ordering="AFTER"
    side="BOTH"